# Generated by Django 3.2.7 on 2021-10-29 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=240, null=True)),
                ('image', models.ImageField(blank=True, default='auction images/image_empty.png', null=True, upload_to='auction images')),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ['-opened_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AuctionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='')),
                ('hash', models.CharField(blank=True, max_length=64, null=True)),
                ('tx_id', models.CharField(blank=True, max_length=66, null=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='auctions.auction')),
            ],
            options={
                'verbose_name': 'Auction report',
                'verbose_name_plural': 'Auction reports',
                'ordering': ['-auction__opened_at', 'auction__title'],
            },
        ),
    ]
