# Generated by Django 3.2.7 on 2021-09-16 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='status',
            new_name='enabled',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='created_by',
        ),
        migrations.AddField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='won_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
