# Generated by Django 3.2.7 on 2021-09-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_won_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='closing_date',
            new_name='closed_at',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='updated_at',
        ),
    ]
