# Generated by Django 3.2.7 on 2021-09-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210916_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-closing_date', 'title'], 'verbose_name': 'Auction', 'verbose_name_plural': 'Auctions'},
        ),
    ]
