# Generated by Django 3.2.7 on 2021-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='opening_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
