# Generated by Django 3.2.7 on 2021-10-09 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
