# Generated by Django 3.2.7 on 2021-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='auction images/image_empty.png', null=True, upload_to='auction images'),
        ),
    ]
