# Generated by Django 3.2.7 on 2021-10-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auction_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionreport',
            options={'ordering': ['-auction__opened_at', 'auction__title'], 'verbose_name': 'Auction report', 'verbose_name_plural': 'Auction reports'},
        ),
    ]
